#include "dinner.h"
const char *const dinner_categories[] = {"火锅", "烧烤", "粤味", "川湘", "面食", "粉类",
                                         "饭类", "日料", "韩餐", "西式", "轻食", "小吃快餐"};
const char *const dinner_modes[] = {"随便吃", "省钱模式", "清淡模式", "重口模式", "聚餐模式"};
const char *const dinner_budgets[] = {"不限", "￥ 省一点", "￥￥ 正常吃", "￥￥￥ 吃顿好的"};
const char *const dinner_diets[] = {"辣", "海鲜", "牛羊肉", "生食", "油炸"};
/* Tags describe common recipes for a game, not ingredient/allergen guarantees. */
const food_t dinner_foods[FOOD_COUNT] = {
    {"重庆火锅", 0, 3, SPICY | OILY | BEEF_LAMB | SHARE},
    {"潮汕牛肉火锅", 0, 3, BEEF_LAMB | SHARE},
    {"椰子鸡", 0, 3, SHARE},
    {"番茄火锅", 0, 2, SHARE},
    {"酸菜鱼火锅", 0, 2, SPICY | OILY | SHARE},
    {"烤串", 1, 2, SPICY | OILY | BEEF_LAMB | SHARE},
    {"韩式烤肉", 1, 3, OILY | BEEF_LAMB | SHARE},
    {"烤鱼", 1, 2, SPICY | OILY | SHARE},
    {"烤鸡", 1, 2, OILY | SHARE},
    {"烧烤拼盘", 1, 3, SPICY | OILY | SEAFOOD | BEEF_LAMB | SHARE},
    {"烧腊饭", 2, 2, OILY},
    {"煲仔饭", 2, 2, OILY},
    {"云吞面", 2, 1, SEAFOOD},
    {"肠粉", 2, 1, 0},
    {"砂锅粥", 2, 2, SEAFOOD | SHARE},
    {"水煮鱼", 3, 2, SPICY | OILY | SHARE},
    {"麻婆豆腐", 3, 1, SPICY | OILY | BEEF_LAMB},
    {"辣椒炒肉", 3, 2, SPICY | OILY},
    {"酸菜鱼", 3, 2, SPICY | OILY | SHARE},
    {"口水鸡", 3, 2, SPICY | OILY},
    {"兰州牛肉面", 4, 1, BEEF_LAMB},
    {"重庆小面", 4, 1, SPICY | OILY},
    {"炸酱面", 4, 1, 0},
    {"刀削面", 4, 1, 0},
    {"热干面", 4, 1, 0},
    {"螺蛳粉", 5, 1, SPICY | FRIED},
    {"桂林米粉", 5, 1, 0},
    {"湖南米粉", 5, 1, SPICY},
    {"过桥米线", 5, 2, 0},
    {"牛肉河粉", 5, 1, BEEF_LAMB},
    {"炒饭", 6, 1, OILY},
    {"咖喱饭", 6, 2, 0},
    {"盖浇饭", 6, 1, 0},
    {"海南鸡饭", 6, 2, 0},
    {"黄焖鸡米饭", 6, 2, 0},
    {"寿司", 7, 2, SEAFOOD | RAW},
    {"日式拉面", 7, 2, OILY},
    {"鳗鱼饭", 7, 3, 0},
    {"天妇罗", 7, 2, SEAFOOD | FRIED | OILY},
    {"日式咖喱", 7, 2, 0},
    {"石锅拌饭", 8, 2, SPICY},
    {"部队锅", 8, 2, SPICY | OILY | SHARE},
    {"韩式炸鸡", 8, 2, SPICY | FRIED | OILY | SHARE},
    {"韩国冷面", 8, 2, BEEF_LAMB},
    {"泡菜汤", 8, 1, SPICY},
    {"汉堡", 9, 2, BEEF_LAMB | OILY},
    {"披萨", 9, 2, OILY | SHARE},
    {"意大利面", 9, 2, 0},
    {"牛排", 9, 3, BEEF_LAMB},
    {"三明治", 9, 1, 0},
    {"沙拉", 10, 2, 0},
    {"鸡胸肉饭", 10, 2, 0},
    {"波奇饭", 10, 2, SEAFOOD | RAW},
    {"白粥", 10, 1, 0},
    {"蔬菜汤", 10, 1, 0},
    {"麻辣烫", 11, 1, SPICY | OILY},
    {"饺子", 11, 1, 0},
    {"馄饨", 11, 1, 0},
    {"肉夹馍", 11, 1, OILY},
    {"炸鸡", 11, 2, FRIED | OILY}};
_Static_assert(sizeof(dinner_categories) / sizeof(*dinner_categories) == CATEGORY_COUNT,
               "categories");
_Static_assert(sizeof(dinner_foods) / sizeof(*dinner_foods) == FOOD_COUNT, "foods");
