#!/usr/bin/env python3
"""Reproducible 2-bpp LVGL font subset. Requires Pillow 12.3.0, fonttools 4.60.1."""
from pathlib import Path
import argparse, re, json, hashlib
from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont
from fontTools import subset
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'assets/fonts'
def inventory():
    chars=set(chr(c) for c in range(32,127))
    for path in sorted((ROOT/'main').glob('dinner_*.c')):
        for literal in re.findall(r'"((?:[^"\\]|\\.)*)"',path.read_text()):
            chars.update(c for c in literal if ord(c)>=32)
    return sorted(chars,key=ord)
def main():
    p=argparse.ArgumentParser();p.add_argument('--source',type=Path,default=OUT/'dinner_subset.otf');a=p.parse_args()
    chars=inventory();font=TTFont(a.source);missing=set(map(ord,chars))-font.getBestCmap().keys()
    if missing:raise SystemExit(f'Missing codepoints: {sorted(missing)}')
    opts=subset.Options();opts.recalc_timestamp=False
    sub=subset.Subsetter(options=opts);sub.populate(unicodes=list(map(ord,chars)));sub.subset(font)
    OUT.mkdir(parents=True,exist_ok=True);font.save(OUT/'dinner_subset.otf')
    source=OUT/'dinner_subset.otf'
    for size in (14,20,30):
        f=ImageFont.truetype(str(source),size);bitmap=[];desc=['{0}']
        for ch in chars:
            l,t,r,b=f.getbbox(ch,anchor='ls');w,h=r-l,b-t
            im=Image.new('L',(max(1,w),max(1,h)));ImageDraw.Draw(im).text((-l,-t),ch,font=f,fill=255,anchor='ls')
            pixels=[min(3,(v+42)//85) for v in im.getdata()] if w*h else []
            offset=len(bitmap)
            for i in range(0,len(pixels),4):
                group=pixels[i:i+4]+[0]*4;bitmap.append(sum(group[j]<<(6-2*j) for j in range(4)))
            desc.append(f'{{.bitmap_index={offset},.adv_w={round(f.getlength(ch)*16)},.box_w={w},.box_h={h},.ofs_x={l},.ofs_y={-b}}}')
        name=f'dinner_font_{size}'
        hexbytes=',\n'.join(','.join(f'0x{x:02x}' for x in bitmap[i:i+20]) for i in range(0,len(bitmap),20))
        points=','.join(str(ord(c)-32) for c in chars)
        descriptors=',\n'.join(desc)
        content=f'''/* Generated by tools/generate_dinner_fonts.py; Noto Sans SC. Copyright (c) 2014-2021 Adobe. SIL OFL 1.1; see OFL.txt. */
#include "lvgl.h"
static const uint8_t bitmap[]={{ {hexbytes} }};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[]={{ {descriptors} }};
static const uint16_t unicode_list[]={{ {points} }};
static const lv_font_fmt_txt_cmap_t cmaps[]={{ {{.range_start=32,.range_length={ord(chars[-1])-31},.glyph_id_start=1,.unicode_list=unicode_list,.list_length={len(chars)},.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}} }};
static const lv_font_fmt_txt_dsc_t dsc={{.glyph_bitmap=bitmap,.glyph_dsc=glyphs,.cmaps=cmaps,.cmap_num=1,.bpp=2,.bitmap_format=0}};
const lv_font_t {name}={{.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height={size+8},.base_line=6,.dsc=&dsc}};
'''
        (OUT/f'{name}.c').write_text(content)
        print(name,len(chars),'glyphs',len(bitmap),'bitmap bytes')
    (OUT/'dinner_font_inventory.c').write_text('#include <stdint.h>\nconst uint32_t dinner_font_codepoints[]={'+','.join(str(ord(c)) for c in chars)+'};\nconst unsigned dinner_font_codepoint_count='+str(len(chars))+';\n')
    (OUT/'inventory.json').write_text(json.dumps({'characters':''.join(chars),'codepoints':list(map(ord,chars)),'sizes':[14,20,30],'bpp':2,'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest()},ensure_ascii=False,indent=2)+'\n')
if __name__=='__main__':main()
